# Generated by Django 5.1.7 on 2025-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='source_revenue_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
